import numpy as np
from scipy.ndimage import gaussian_filter, median_filter
from skimage.filters import threshold_otsu
from scipy import stats


class KymoController:
    def __init__(self, analyzer):
        self.analyzer = analyzer

        # Smoothing
        self.smooth_mode = "Gaussian"
        self.sigma = 3
        self.median_size = 3

        # Calibration
        self.pixel_size = None
        self.time_per_frame = 1.0
        self.z_max = 1.0

        # Brightness/contrast
        self.brightness = 0.0
        self.contrast = 1.0
           
        # Edge detection sensitivity
        self.edge_sensitivity = 0.5   # 0 = permissive, 1 = strict

        # Z threshold (0–1, on normalized image)
        self.z_threshold = 0.

        # Data
        self.kymo_raw = None
        self.kymo_smooth = None
        self.kymo_roi = None
        self.roi_bounds = None
        self.path = None

        # Smoothing cache
        self._last_smooth_params = None

        # Template profiles (injected from manager)
        self.profiles = []

    # -------------------------
    # LOADING
    # -------------------------
    def load_kymo(self, path, pixel_size):
        self.path = path
        self.pixel_size = pixel_size

        self.kymo_raw = self.analyzer.load_raw_kymo(path)
        self.kymo_smooth = self.kymo_raw.copy()
        self.kymo_roi = self.kymo_smooth.copy()

        img = self.apply_brightness_contrast(self.kymo_roi)
        self.analyzer.draw_image(img, pixel_size=self.pixel_size, time_per_frame=self.time_per_frame)

    def load_kymo_array(self, kymo, pixel_size=1.0, time_per_frame=1.0):
        """Load a kymograph generated by the Qt panel without writing a file."""
        self.pixel_size = pixel_size
        self.time_per_frame = time_per_frame
        self.kymo_raw = self.analyzer.load_raw_kymo_array(kymo)
        self.kymo_smooth = self.kymo_raw.copy()
        self.kymo_roi = self.kymo_smooth.copy()
        self.analyzer.draw_image(
            self.kymo_roi, pixel_size=pixel_size, time_per_frame=time_per_frame
        )

    # -------------------------
    # Z CALIBRATION
    # -------------------------
    def set_z_max(self, value):
        try:
            self.z_max = float(value)
            print(f"Z calibration updated: 0 → {self.z_max}")
            self.apply_smoothing()
        except:
            print("Invalid value for Z.")

    def set_z_threshold(self, value):
        try:
            self.z_threshold = float(value)
        except:
            pass

    # -------------------------
    # BRIGHTNESS / CONTRAST
    # -------------------------
    def apply_brightness_contrast(self, img):
        if img is None:
            return None

        img = img.astype(float)
        mn = img.min()
        mx = img.max()
        if mx <= mn:
            return img

        img_n = (img - mn) / (mx - mn)
        img_z = img_n * self.z_max

        midpoint = self.z_max / 2
        out = (img_z - midpoint) * self.contrast + midpoint + self.brightness
        out = np.clip(out, 0, self.z_max)

        return out / self.z_max

    # -------------------------
    # SMOOTHING
    # -------------------------
    def set_smoothing_mode(self, mode):
        self.smooth_mode = mode
        self._last_smooth_params = None

    def set_smoothing_param(self, value):
        if self.smooth_mode == "Gaussian":
            self.sigma = int(value)
        elif self.smooth_mode == "Median":
            self.median_size = int(value)
        self._last_smooth_params = None

    def preview_smoothing(self):
        img = self._compute_smoothing()
        img = self.apply_brightness_contrast(img)
        self.analyzer.draw_image(img, preview=True, pixel_size=self.pixel_size, time_per_frame=self.time_per_frame)

    def apply_smoothing(self):
        self.kymo_smooth = self._compute_smoothing()
        self.kymo_roi = self.kymo_smooth.copy()
        img = self.apply_brightness_contrast(self.kymo_roi)
        self.analyzer.draw_image(img, pixel_size=self.pixel_size, time_per_frame=self.time_per_frame)

    def _compute_smoothing(self):
        if self.kymo_raw is None:
            return None

        params = (self.smooth_mode, self.sigma, self.median_size)
        if self._last_smooth_params == params and self.kymo_smooth is not None:
            return self.kymo_smooth

        if self.smooth_mode == "Gaussian":
            out = gaussian_filter(self.kymo_raw, sigma=self.sigma)
        elif self.smooth_mode == "Median":
            out = median_filter(self.kymo_raw, size=self.median_size)
        else:
            out = self.kymo_raw.copy()

        self._last_smooth_params = params
        return out

    # -------------------------
    # ROI
    # -------------------------
    def apply_roi(self, x0, x1, y0, y1):
        x0, x1 = sorted((int(x0), int(x1)))
        y0, y1 = sorted((int(y0), int(y1)))

        self.roi_bounds = (x0, x1, y0, y1)
        self.kymo_roi = self.kymo_smooth[y0:y1, x0:x1]

        img = self.apply_brightness_contrast(self.kymo_roi)
        self.analyzer.draw_image(img, pixel_size=self.pixel_size, time_per_frame=self.time_per_frame)

    def reset_roi(self):
        self.roi_bounds = None
        self.kymo_roi = self.kymo_smooth.copy()

        img = self.apply_brightness_contrast(self.kymo_roi)
        self.analyzer.draw_image(img, pixel_size=self.pixel_size, time_per_frame=self.time_per_frame)

    # -------------------------
    # POLYMER EDGE DETECTION (gradient + templates)
    # -------------------------
    def detect_polymer_edges(self):
        img = self.kymo_roi
        if img is None:
            return None, None, None, None

        H, W = img.shape

        # X-gradient to enhance edges
        grad = np.abs(np.gradient(img, axis=1))
        img_use = grad

        ys = []
        xs_left = []
        xs_right = []

        first_valid_y = None

        for y in range(H):
            row = img_use[y, :].copy()

            # 1) Apply Z threshold on the smoothed image
            base_row = self.kymo_roi[y, :]
            mask_z = base_row >= self.z_threshold
            row = np.where(mask_z, row, 0.0)

            if np.all(row == 0):
                continue

            # 2) Otsu on thresholded row
            try:
                t = threshold_otsu(row[row > 0])
            except Exception:
                continue

            mask = row > t
            idx = np.where(mask)[0]

            if len(idx) == 0:
                continue

            # 3) Connected segments
            segments = []
            start = idx[0]
            for i in range(1, len(idx)):
                if idx[i] != idx[i - 1] + 1:
                    segments.append((start, idx[i - 1]))
                    start = idx[i]
            segments.append((start, idx[-1]))

            seg_lengths = [(b - a) for (a, b) in segments]
            max_len = max(seg_lengths)

            # 4) Length filtering (edge_sensitivity)
            threshold_len = (1 - self.edge_sensitivity) * max_len
            candidates = [seg for seg in segments if (seg[1] - seg[0]) >= threshold_len]

            if not candidates:
                continue

            if first_valid_y is None:
                first_valid_y = y

            # 5) Template matching if available
            best = self._select_segment_with_templates(candidates, y)
            if best is None:
                best = candidates[0]

            xs_left.append(best[0])
            xs_right.append(best[1])
            ys.append(y)

        if not ys:
            return None, None, None, None

        ys = np.array(ys)
        xs_left = np.array(xs_left)
        xs_right = np.array(xs_right)

        # 6) Trim to start at first valid row
        if first_valid_y is not None:
            mask_valid = ys >= first_valid_y
            ys = ys[mask_valid]
            xs_left = xs_left[mask_valid]
            xs_right = xs_right[mask_valid]

        if len(ys) == 0:
            return None, None, None, None

        # Use segment center as robust measurement
        values = (xs_left + xs_right) / 2.0 * self.pixel_size

        return ys, xs_left, xs_right, values


    def _select_segment_with_templates(self, segments, y):
        if not self.profiles:
            return None

        best_seg = None
        best_dist = 1e9

        for seg in segments:
            a, b = seg
            x_mid = (a + b) / 2.0

            for profile in self.profiles:
                ys = profile.get("ys", None)
                xs = profile.get("xs", None)
                if ys is None or xs is None or len(ys) == 0:
                    continue

                idx = np.argmin(np.abs(ys - y))
                x_template = xs[idx]

                dist = abs(x_mid - x_template)
                if dist < best_dist:
                    best_dist = dist
                    best_seg = seg

        return best_seg

    # -------------------------
    # SLOPE DETECTION
    # -------------------------
    def detect_slope_segments(self, ys, values, min_len=5, slope_threshold=-0.02):
        if ys is None or values is None or len(ys) < 2:
            return []

        slopes = np.diff(values)
        segments = []
        start = None

        for i in range(len(slopes)):
            if slopes[i] < slope_threshold:
                if start is None:
                    start = i
            else:
                if start is not None:
                    if i - start >= min_len:
                        segments.append((start, i))
                    start = None

        if start is not None and (len(slopes) - start) >= min_len:
            segments.append((start, len(slopes) - 1))

        return segments

    # -------------------------
    # LINEAR FIT
    # -------------------------
    def compute_fit_for_segment(self, ys, values, i0, i1):
        if ys is None or values is None:
            return None
        if i1 <= i0:
            return None

        t_sel = ys[i0:i1 + 1] * self.time_per_frame
        v_sel = values[i0:i1 + 1]
        if len(t_sel) < 2:
            return None

        slope, intercept, r, p, stderr = stats.linregress(t_sel, v_sel)
        return slope, intercept, r, p, stderr

    def compute_disassembly_rate(self, frame_indices, lengths_nm):
        """Fit length versus time and return the rate in nm/s."""
        if frame_indices is None or lengths_nm is None:
            return None
        frame_indices = np.asarray(frame_indices, dtype=float)
        lengths_nm = np.asarray(lengths_nm, dtype=float)
        if frame_indices.size < 2 or frame_indices.shape != lengths_nm.shape:
            return None
        if self.time_per_frame <= 0:
            return None
        slope, intercept, r, p, stderr = stats.linregress(
            frame_indices * self.time_per_frame, lengths_nm
        )
        return {
            "rate_nm_s": float(slope),
            "intercept_nm": float(intercept),
            "r_value": float(r),
            "p_value": float(p),
            "stderr_nm_s": float(stderr),
        }

    # -------------------------
    # PHASE CLASSIFICATION
    # -------------------------
    def classify_phase(self, slope, growth_thr=0.02, shrink_thr=-0.02):
        if slope >= growth_thr:
            return "growth"
        elif slope <= shrink_thr:
            return "catastrophe"
        else:
            return "pause"

    # -------------------------
    # MANUAL PICKING (reused for templates)
    # -------------------------
    
    def manual_pick_profile(self, p0, p1):
        # p0 and p1 are in physical coordinates: (nm, s)
        x0_nm, y0_s = p0
        x1_nm, y1_s = p1

        # Convert to pixels
        px0 = x0_nm / self.pixel_size
        px1 = x1_nm / self.pixel_size

        py0 = y0_s / self.time_per_frame
        py1 = y1_s / self.time_per_frame

        # Pixel range in Y
        ys_pix = np.arange(int(min(py0, py1)), int(max(py0, py1)))
        if len(ys_pix) == 0:
            return np.array([]), np.array([])

        # Interpolation in pixels
        xs_pix = np.interp(ys_pix, [py0, py1], [px0, px1])

        # Clipping
        ys_pix = np.clip(ys_pix.astype(int), 0, self.kymo_roi.shape[0] - 1)
        xs_pix = np.clip(xs_pix.astype(int), 0, self.kymo_roi.shape[1] - 1)

        return ys_pix, xs_pix
